# learn-cassandra docker-compose

cassandra:
  image: library/cassandra:3.2
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
  environment:
    # CASSANDRA_SEEDS: ""
    CASSANDRA_CLUSTER_NAME: "just-learning"
  volumes:
    - /opt/learn-cassandra/just-learning:/var/lib/cassandra

opscenter:
  image: poklet/opscenter
  ports:
    - "8888:8888"
  links:
    - cassandra
