# learn-cassandra docker-compose

cassandra:
  image: library/cassandra:3.0
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
  net: host
  environment:
    CASSANDRA_SEEDS: "localhost"
    CASSANDRA_CLUSTER_NAME: "just-learning"
  volumes:
    - /opt/learn-cassandra/just-learning:/var/lib/cassandra

opscenter:
  image: poklet/opscenter
  ports:
    - "8888:8888"
  links:
    - cassandra
